name: Deploy

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{github.event.ref}}
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
